"""empty message

Revision ID: 2b38cb097f7c
Revises: 
Create Date: 2019-05-06 14:34:16.447585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b38cb097f7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Member')
    op.drop_table('Message')
    op.drop_table('Chat')
    op.drop_table('User')
    op.drop_table('Attachment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attachment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Attachment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Attachment_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nick', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('nick', name='User_nick_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Chat',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Chat_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('is_group_chat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('unread', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Chat_pkey'),
    sa.UniqueConstraint('key', name='Chat_key_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Message',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Message_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Message_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Member',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Member_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_unread_message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['Chat.id'], name='Member_chat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_unread_message_id'], ['Message.id'], name='Member_last_unread_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Member_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Member_pkey')
    )
    # ### end Alembic commands ###
